/*
 * LED.c
 *
 * Created: 11/7/2022 3:48:40 PM
 *  Author: Dell
 */ 

#include "LED.h"
//LED_init function is used to set the pin as digital OUTPUT pin to drive a LED
void LED_init(uint8_t ledPort, uint8_t ledPin){
	pinMode(ledPort,ledPin,OUTPUT);
}
//LED_on function is used to set the desired LED to be on by putting a HIGH signal on its pin
void LED_on(uint8_t ledPort, uint8_t ledPin){
	digitalWrite(ledPort,ledPin,HIGH);
}
//LED_off function is used to set the desired LED to be off by putting a LOW signal on its pin
void LED_off(uint8_t ledPort, uint8_t ledPin){
	digitalWrite(ledPort,ledPin,LOW);
}
//LED_toggle function is used to toggle the state of the Desired LED by toggling the corresponding pin
void LED_toggle(uint8_t ledPort, uint8_t ledPin){
	digitalToggle(ledPort,ledPin);
}
void LEDTestFunctionOn(){
	LED_init(PORT_A,0);
	LED_init(PORT_A,1);
	LED_init(PORT_A,2);
	LED_init(PORT_A,3);
	LED_init(PORT_A,4);
	LED_init(PORT_A,5);
	LED_init(PORT_A,6);
	LED_init(PORT_A,7);
	LED_init(PORT_B,0);
	LED_init(PORT_B,1);
	LED_init(PORT_B,2);
	LED_init(PORT_B,3);
	LED_init(PORT_B,4);
	LED_init(PORT_B,5);
	LED_init(PORT_B,6);
	LED_init(PORT_B,7);
	LED_init(PORT_C,0);
	LED_init(PORT_C,1);
	LED_init(PORT_C,2);
	LED_init(PORT_C,3);
	LED_init(PORT_C,4);
	LED_init(PORT_C,5);
	LED_init(PORT_C,6);
	LED_init(PORT_C,7);
	LED_init(PORT_D,0);
	LED_init(PORT_D,1);
	LED_init(PORT_D,2);
	LED_init(PORT_D,3);
	LED_init(PORT_D,4);
	LED_init(PORT_D,5);
	LED_init(PORT_D,6);
	LED_init(PORT_D,7);
	LED_on(PORT_A,0);
	LED_on(PORT_A,1);
	LED_on(PORT_A,2);
	LED_on(PORT_A,3);
	LED_on(PORT_A,4);
	LED_on(PORT_A,5);
	LED_on(PORT_A,6);
	LED_on(PORT_A,7);
	LED_on(PORT_B,0);
	LED_on(PORT_B,1);
	LED_on(PORT_B,2);
	LED_on(PORT_B,3);
	LED_on(PORT_B,4);
	LED_on(PORT_B,5);
	LED_on(PORT_B,6);
	LED_on(PORT_B,7);
	LED_on(PORT_B,0);
	LED_on(PORT_C,1);
	LED_on(PORT_C,2);
	LED_on(PORT_C,3);
	LED_on(PORT_C,4);
	LED_on(PORT_C,5);
	LED_on(PORT_C,6);
	LED_on(PORT_C,7);
	LED_on(PORT_D,0);
	LED_on(PORT_D,1);
	LED_on(PORT_D,2);
	LED_on(PORT_D,3);
	LED_on(PORT_D,4);
	LED_on(PORT_D,5);
	LED_on(PORT_D,6);
	LED_on(PORT_D,7);
}
void LEDTestFunctionOff(){
	LED_init(PORT_A,0);
	LED_init(PORT_A,1);
	LED_init(PORT_A,2);
	LED_init(PORT_A,3);
	LED_init(PORT_A,4);
	LED_init(PORT_A,5);
	LED_init(PORT_A,6);
	LED_init(PORT_A,7);
	LED_init(PORT_B,0);
	LED_init(PORT_B,1);
	LED_init(PORT_B,2);
	LED_init(PORT_B,3);
	LED_init(PORT_B,4);
	LED_init(PORT_B,5);
	LED_init(PORT_B,6);
	LED_init(PORT_B,7);
	LED_init(PORT_C,0);
	LED_init(PORT_C,1);
	LED_init(PORT_C,2);
	LED_init(PORT_C,3);
	LED_init(PORT_C,4);
	LED_init(PORT_C,5);
	LED_init(PORT_C,6);
	LED_init(PORT_C,7);
	LED_init(PORT_D,0);
	LED_init(PORT_D,1);
	LED_init(PORT_D,2);
	LED_init(PORT_D,3);
	LED_init(PORT_D,4);
	LED_init(PORT_D,5);
	LED_init(PORT_D,6);
	LED_init(PORT_D,7);
	LED_off(PORT_A,0);
	LED_off(PORT_A,1);
	LED_off(PORT_A,2);
	LED_off(PORT_A,3);
	LED_off(PORT_A,4);
	LED_off(PORT_A,5);
	LED_off(PORT_A,6);
	LED_off(PORT_A,7);
	LED_off(PORT_B,0);
	LED_off(PORT_B,1);
	LED_off(PORT_B,2);
	LED_off(PORT_B,3);
	LED_off(PORT_B,4);
	LED_off(PORT_B,5);
	LED_off(PORT_B,6);
	LED_off(PORT_B,7);
	LED_off(PORT_B,0);
	LED_off(PORT_C,1);
	LED_off(PORT_C,2);
	LED_off(PORT_C,3);
	LED_off(PORT_C,4);
	LED_off(PORT_C,5);
	LED_off(PORT_C,6);
	LED_off(PORT_C,7);
	LED_off(PORT_D,0);
	LED_off(PORT_D,1);
	LED_off(PORT_D,2);
	LED_off(PORT_D,3);
	LED_off(PORT_D,4);
	LED_off(PORT_D,5);
	LED_off(PORT_D,6);
	LED_off(PORT_D,7);
}
void LEDTestFunctionToggle(){
	LED_init(PORT_A,0);
	LED_init(PORT_A,1);
	LED_init(PORT_A,2);
	LED_init(PORT_A,3);
	LED_init(PORT_A,4);
	LED_init(PORT_A,5);
	LED_init(PORT_A,6);
	LED_init(PORT_A,7);
	LED_init(PORT_B,0);
	LED_init(PORT_B,1);
	LED_init(PORT_B,2);
	LED_init(PORT_B,3);
	LED_init(PORT_B,4);
	LED_init(PORT_B,5);
	LED_init(PORT_B,6);
	LED_init(PORT_B,7);
	LED_init(PORT_C,0);
	LED_init(PORT_C,1);
	LED_init(PORT_C,2);
	LED_init(PORT_C,3);
	LED_init(PORT_C,4);
	LED_init(PORT_C,5);
	LED_init(PORT_C,6);
	LED_init(PORT_C,7);
	LED_init(PORT_D,0);
	LED_init(PORT_D,1);
	LED_init(PORT_D,2);
	LED_init(PORT_D,3);
	LED_init(PORT_D,4);
	LED_init(PORT_D,5);
	LED_init(PORT_D,6);
	LED_init(PORT_D,7);
	LED_toggle(PORT_A,0);
	LED_toggle(PORT_A,1);
	LED_toggle(PORT_A,2);
	LED_toggle(PORT_A,3);
	LED_toggle(PORT_A,4);
	LED_toggle(PORT_A,5);
	LED_toggle(PORT_A,6);
	LED_toggle(PORT_A,7);
	LED_toggle(PORT_B,0);
	LED_toggle(PORT_B,1);
	LED_toggle(PORT_B,2);
	LED_toggle(PORT_B,3);
	LED_toggle(PORT_B,4);
	LED_toggle(PORT_B,5);
	LED_toggle(PORT_B,6);
	LED_toggle(PORT_B,7);
	LED_toggle(PORT_B,0);
	LED_toggle(PORT_C,1);
	LED_toggle(PORT_C,2);
	LED_toggle(PORT_C,3);
	LED_toggle(PORT_C,4);
	LED_toggle(PORT_C,5);
	LED_toggle(PORT_C,6);
	LED_toggle(PORT_C,7);
	LED_toggle(PORT_D,0);
	LED_toggle(PORT_D,1);
	LED_toggle(PORT_D,2);
	LED_toggle(PORT_D,3);
	LED_toggle(PORT_D,4);
	LED_toggle(PORT_D,5);
	LED_toggle(PORT_D,6);
	LED_toggle(PORT_D,7);
}
